In [1]:
pip install nltk

     |████████████████████████████████| 1.4MB 3.2MB/s eta 0:00:01     |█████████▍                      | 419kB 3.2MB/s eta 0:00:01
     |████████████████████████████████| 307kB 7.3MB/s eta 0:00:01
     |████████████████████████████████| 675kB 16.9MB/s eta 0:00:01
     |████████████████████████████████| 81kB 7.9MB/s  eta 0:00:01
  Stored in directory: /home/jupyterlab/.cache/pip/wheels/ae/8c/3f/b1fe0ba04555b08b57ab52ab7f86023639a526d8bc8d384306
Successfully built nltk
Note: you may need to restart the kernel to use updated packages.


In [2]:
from nltk.tokenize import TweetTokenizer

def tokenize(text): 
    tknzr = TweetTokenizer()
    return tknzr.tokenize(text)

In [6]:
import pickle
model = pickle.load(open('svm_model.pkl','rb'))
test = ["im very satisfied with the service"]

In [7]:
import numpy as np

def tanh(x, derivative=False):
    if (derivative == True):
        return (1 - (x ** 2))
    return np.tanh(x)


In [8]:
test = model.predict_proba(test)

flat = tanh(test)
print(test)
flat = flat.tolist()

for i in flat:
    if i[0] > i[1]:
        num = tanh(i[0]) 
    else:
        num = tanh(-i[1])
    

    print(num)
    

[[0.6612655 0.3387345]]
0.5220873512732351


In [9]:
import pandas as pd
import nltk

In [10]:
df = pd.read_csv('opinion_survey.csv')
df = df.replace(np.nan, 'Neutral', regex=True) ### Some values are missing, use "Neutral" for missing values
df = df.drop(df.columns[[0]],axis=1) ### Drop extra index
test_df = df.iloc[0:, 0:] # Just for renaming purposes so that df variable can be used for testing
test_df.head()

I can easily log-in and log-out my Canvas account. (Please write your views relating your answer above.)  \
0                                              i can                                                         
1                      i have no problems in log in                                                          
2                         I have no problems with it                                                         
3                   i dont have problem in my canvas                                                         
4                                 i have no problems                                                         

  I can access my course using the mobile Canvas app. (Please write your views about this relating to your answer above.)  \
0                                              i can                                                                        
1                                  i have no problem                                                                        
2                        I have no problems with it                                                                         
3  i can easily login my canvas app in my mobile app                                                                        
4                             i can access my course                                                                        

  I can access my Canvas account using the available computers in JRU. (Please write your views about this relating to your answer above.)  \
0                                              i can                                                                                         
1                                  i have no problem                                                                                         
2                        I have no problems with it                                                                                          
3  I can access my Canvas account using the avail...                                                                                         
4                  no problem in accessing my canvas                                                                                         

  I have no issues accessing my Canvas account using the wired internet connection in the computer laboratories. (Please write your views about this relating to your answer above.)  \
0                                              i can                                                                                                                                   
1                                  i have no problem                                                                                                                                   
2                         I have no problems with it                                                                                                                                   
3         i dont have problem in internet connection                                                                                                                                   
4                                    dont have issue                                                                                                                                   

  I can easily get help when I have problems with my Canvas account. (Please write your views about this relating to your answer above.)  \
0                                              i can                                                                                       
1                                  i have no problem                                                                                       
2                         I have no problems with it                                                                                       
3                        i dont have problem with it                    

In [11]:
from pprint import pprint
comp = []
col_range = len(test_df.columns) # number of columns

for i in range(0,1):
    col = test_df.columns[i] # The current column
    test_df['scores'] = test_df[col].apply(lambda x: model.predict_proba([x])) ## Get polarity score of every Column
    list_comp = test_df['scores'].values.tolist()
    arr = []
    print("Sentiment scores from probability")
    for i in list_comp:
        i = i.flatten()
        #print(i[:5])
        if i[0] > i[1]:
            num = tanh(i[0]) 
            arr.append(num)
        else:
            num = tanh(-i[1])
            arr.append(num)
    pprint(list_comp)
    testing = sum(arr)/140
    print("Sentiment Score from aggregated probability results with tanh",testing)
        
    #compound = test_df['scores'].apply(lambda x: tanh(x)) ## Extract the compound from the results
    '''test_df = test_df.drop('scores', 1) # Drop score DF in every iteration
    compound = sum(compound)/140 # Get the mean compound of each columns
    comp.append(compound)''' # Save mean and append to list
    #print(arr)


Sentiment scores from probability
[array([[0.71712754, 0.28287246]]),
 array([[0.45005308, 0.54994692]]),
 array([[0.53655973, 0.46344027]]),
 array([[0.51603465, 0.48396535]]),
 array([[0.53655973, 0.46344027]]),
 array([[0.53655973, 0.46344027]]),
 array([[0.5, 0.5]]),
 array([[0.80802044, 0.19197956]]),
 array([[0.37028954, 0.62971046]]),
 array([[0.48684156, 0.51315844]]),
 array([[0.54624958, 0.45375042]]),
 array([[0.48684156, 0.51315844]]),
 array([[0.44946643, 0.55053357]]),
 array([[0.54624958, 0.45375042]]),
 array([[0.54624958, 0.45375042]]),
 array([[0.43723547, 0.56276453]]),
 array([[0.48732388, 0.51267612]]),
 array([[0.3928404, 0.6071596]]),
 array([[0.3928404, 0.6071596]]),
 array([[0.86467965, 0.13532035]]),
 array([[0.5, 0.5]]),
 array([[0.48684156, 0.51315844]]),
 array([[0.38391521, 0.61608479]]),
 array([[0.43723547, 0.56276453]]),
 array([[0.62250717, 0.37749283]]),
 array([[0.34300759, 0.65699241]]),
 array([[0.48694571, 0.51305429]]),
 array([[0.42060433, 0.579